### ISSUE TITLE
Release into Jade

### ISSUE THREAD

**Issue by davetcoleman** [lrse/ros-keyboard#3]
Could we get this package released in jade? I have some downstream packages that I cannot release yet because of it.

Thanks!

**Comment by v01d** [comment]
Sure, glad to know it is used. Give me some days and I will make the release.

**Comment by davetcoleman** [comment]
Great!

**Comment by v01d** [comment]
Done!

**Comment by davetcoleman** [comment]
Thanks - I'm using this package here: https://github.com/davetcoleman/tf_keyboard_cal

**Comment by davetcoleman** [comment]
And you've enabled: https://github.com/ros/rosdistro/pull/9971

**Comment by v01d** [comment]
Cool =)
